volumes:
  igraj-kosarku-data:
    name: igraj-kosarku-data

services:
  igraj-kosarku-db:
    image: postgres:latest
    container_name: igraj-kosarku-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=igraj-kosarku
      - POSTGRES_PASSWORD=dxDGNE5CvNZzKx8JzSJWFJTC
      - POSTGRES_DB=igraj_kosarku
      - POSTGRES_URL=igraj-kosarku-db
    ports:
      - 5432:5432
    networks: 
      - igraj-kosarku-network
    volumes:
      - igraj-kosarku-data:/var/lib/postgresql

networks: 
  igraj-kosarku-network:
    name: igraj-kosarku-network
    driver: bridge
